services:
  cloudflared:
    image: cloudflare/cloudflared:2026.7.2@sha256:4f6655284ab3d252b7f28fedb19fe6c8fc82ee5b1295c20ac74d475e5398a52d
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host
    command: tunnel --no-autoupdate --metrics 127.0.0.1:20241 run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
