-- =============================================================================
-- V1__baseline_schema.sql
--
-- Baseline del schema de produccion (auditado 2026-08-07).
-- Representa EXACTAMENTE el estado actual de PostgreSQL 17 de produccion:
--   usuarios, tipos_tarea, tareas
-- Identity, PK, FK, unique, CHECK urgencia, nullable y longitudes.
--
-- Reglas de este PR:
--   - Sin datos de usuario.
--   - Sin DROP ni ALTER destructivo.
--   - Una vez publicado, este archivo es INMUTABLE (Flyway comprueba checksum).
--
-- Uso:
--   - DB vacia: Flyway ejecuta V1 y crea todo el schema.
--   - DB existente (produccion): se marca con Flyway baseline a version 1
--     y V1 NO se ejecuta sobre tablas ya existentes.
-- =============================================================================

CREATE TABLE usuarios (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL,
    email    varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    CONSTRAINT ukm2dvbwfge291euvmk6vkkocao UNIQUE (username),
    CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email)
);

CREATE TABLE tipos_tarea (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      varchar(50)  NOT NULL,
    descripcion varchar(500),
    color       varchar(7)   NOT NULL,
    usuario_id  bigint NOT NULL,
    CONSTRAINT fkdyvls5v39dmydwoj1faxm53iu
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE tareas (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo        varchar(255) NOT NULL,
    descripcion   varchar(500),
    fecha         date         NOT NULL,
    completada    boolean,
    urgencia      integer      NOT NULL,
    tipo_tarea_id bigint       NOT NULL,
    usuario_id    bigint       NOT NULL,
    CONSTRAINT tareas_urgencia_check CHECK (urgencia >= 0 AND urgencia <= 2),
    CONSTRAINT fk1mdqpli1pnt3nvm0soer1mf9q
        FOREIGN KEY (tipo_tarea_id) REFERENCES tipos_tarea (id),
    CONSTRAINT fkdmoaxl7yv4q6vkc9h32wvbddr
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
